### PR TITLE
Protobuf submodule

### PR DESCRIPTION
**Pull request by Leo-Nogismus**
Added the AERA_Protobuf repo as a submodule for AERA_Webots.

### CODE REVIEW

**Comment by jefft0** [comment]
Hi @Leo-Nogismus . I get the following build errors:

1>c:\users\jeff\temp\aera_webots\controllers\aera_hand_controller_protobuf\hand_grab_sphere_controller.cpp(50): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'tcp_io_device::MetaData'
1>c:\users\jeff\temp\aera_webots\controllers\aera_hand_controller_protobuf\hand_grab_sphere_controller.cpp(50): note: No constructor could take the source type, or constructor overload resolution was ambiguous
1>c:\users\jeff\temp\aera_webots\controllers\aera_hand_controller_protobuf\hand_grab_sphere_controller.cpp(51): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'tcp_io_device::MetaData'
1>c:\users\jeff\temp\aera_webots\controllers\aera_hand_controller_protobuf\hand_grab_sphere_controller.cpp(51): note: No constructor could take the source type, or constructor overload resolution was ambiguous
1>c:\users\jeff\temp\aera_webots\controllers\aera_hand_controller_protobuf\hand_grab_sphere_controller.cpp(52): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'tcp_io_device::MetaData'
1>c:\users\jeff\temp\aera_webots\controllers\aera_hand_controller_protobuf\hand_grab_sphere_controller.cpp(52): note: No constructor could take the source type, or constructor overload resolution was ambiguous
1>c:\users\jeff\temp\aera_webots\controllers\aera_hand_controller_protobuf\hand_grab_sphere_controller.cpp(53): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'tcp_io_device::MetaData'
1>c:\users\jeff\temp\aera_webots\controllers\aera_hand_controller_protobuf\hand_grab_sphere_controller.cpp(53): note: No constructor could take the source type, or constructor overload resolution was ambiguous
1>c:\users\jeff\temp\aera_webots\controllers\aera_hand_controller_protobuf\hand_grab_sphere_controller.cpp(56): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'tcp_io_device::MetaData'
1>c:\users\jeff\temp\aera_webots\controllers\aera_hand_controller_protobuf\hand_grab_sphere_controller.cpp(56): note: No constructor could take the source type, or constructor overload resolution was ambiguous
1>c:\users\jeff\temp\aera_webots\controllers\aera_hand_controller_protobuf\hand_grab_sphere_controller.cpp(57): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'tcp_io_device::MetaData'
1>c:\users\jeff\temp\aera_webots\controllers\aera_hand_controller_protobuf\hand_grab_sphere_controller.cpp(57): note: No constructor could take the source type, or constructor overload resolution was ambiguous
1>c:\users\jeff\temp\aera_webots\controllers\aera_hand_controller_protobuf\hand_grab_sphere_controller.cpp(58): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'tcp_io_device::MetaData'
1>c:\users\jeff\temp\aera_webots\controllers\aera_hand_controller_protobuf\hand_grab_sphere_controller.cpp(58): note: No constructor could take the source type, or constructor overload resolution was ambiguous

**Comment by jefft0** [comment]
I also noticed that this pull request branch is not using the latest commit of the AERA_Protobuf submodule.

**Comment by Leo-Nogismus** [comment]
I don't know why it worked on my machine, after re-pulling everything, I had the same error. Will update AERA_Protobuf and AERA_Webots in a second.

**Comment by Leo-Nogismus** [comment]
Can you try again? It should build now.

**Review by jefft0 — APPROVED** [review]

**Comment by jefft0** [comment]
I builds and runs for me now. Thanks. Do you want to squash the last commit into the first one? It's up to you. You can merge.

**Comment by jefft0** [comment]
Maybe also squash commit number 5 "Update .gitmodules" into the first commit?

**Pull request merged**
